### ISSUE TITLE
ipad Safari: Non Responsive clicking of icons

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#3]
I have to click on the icons twice to even open a slide on the ipad.

**Comment by CALLVES** [comment]
This is still happening... not sure if this is an ipad thing? The icons you have to click on them twice. Same with the hamburger menu. This is happening on Safari AND FF on ipad...

**Comment by juliafrichbeet** [comment]
Yep, that ipad/iphome thing. It works with mobile events in a different way. I'll try to change code for that

**Comment by CALLVES** [comment]
Thanks just let me know if at some point this becomes a huge problem. I will explain to client.

**Comment by juliafrichbeet** [comment]
It took time to find the reasob, but now I see - that all happend because of tooltips for each icon - please check the screenshot. 
![image](https://cloud.githubusercontent.com/assets/24528105/21263662/c047bb0e-c3a0-11e6-993d-0588ddd995e1.png) 
Now I left this one only for desktop. Iphones/Ipads really work with mobile events in a different way. Please confirm that it's OK now

**Comment by CALLVES** [comment]
It's ok now. Thank you.
